global:
  profile: ambient

cni:
  ambient:
    enabled: true
    enablementSelectors:
    - namespaceSelector:
        matchExpressions:
        # Exclude certain namespaces by name
        - key: kubernetes.io/metadata.name
          operator: NotIn
          values:
            # Kubernetes core systems cannot be encrypted
            - "kube-system"
            - "kube-public"
            - "kube-node-lease"
            - "kubernetes-dashboard"

            - "istio-system" # Istio cannot encrypt its own traffic because of a routing loop
            - "gke-managed-system" # Google-specific managed systems

        # Exclude namespaces explicitly labeled to opt-out
        - key: psp.io/encryption
          operator: NotIn
          values: ["false"]

      podSelector:
        matchExpressions:
        # Enroll all pods by default, unless explicitly opted-out
        - key: psp.io/encryption
          operator: NotIn
          values: ["false"]
